---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-deployment
  template:
    metadata:
      labels:
        app: hello-deployment
    spec:
      containers:
        - image: 123497/hello-deployment:v1
          name: hello-deployment
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: hello-deployment
spec:
  type: NodePort
  selector:
    app: hello-deployment
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32700
